### ISSUE TITLE
VM Details not fetched, and VM not working day after.

### ISSUE THREAD

**Issue by Hemant2000-karens** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#10]
Failed to Get details of VM Installed and running Properly.

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; virsh domblkinfo --domain UbuntuMininet --all --human' with exit code '1':`

Error showed this, and yesterday I successfully using vm and today I am getting this error.

```
Unable to - poweronCannot access storage file '/srv/dev-disk-by-uuid-17cce31e-e524-4393-a5e4-cead68278c83/UbuntuMininet.img': No such file or directory

OMV\Exception: Unable to - poweronCannot access storage file '/srv/dev-disk-by-uuid-17cce31e-e524-4393-a5e4-cead68278c83/UbuntuMininet.img': No such file or directory in /usr/share/openmediavault/engined/rpc/kvm.inc:2182
Stack trace:
#0 [internal function]: OMVRpcServiceKvm->doCommand(Array, Array)
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('doCommand', Array, Array)
#3 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Kvm', 'doCommand', Array, Array, 1)
#4 {main}
```

**Comment by ryecoaaron** [comment]
This really isn't a problem with the plugin and would be a better forum post.

You are putting your VM files in the root of the filesystem?  This could cause permissions issues.

Is /srv/dev-disk-by-uuid-17cce31e-e524-4393-a5e4-cead68278c83/UbuntuMininet.img actually there?
ls -al /srv/dev-disk-by-uuid-17cce31e-e524-4393-a5e4-cead68278c83/UbuntuMininet.img

usb storage?

**Comment by Hemant2000-karens** [comment]
oh Yes!! thank you for your reply, I got the issue, and creator of the issue is me itself. Hope you didn't get disturbed. I tell you that I Panic little shortly.
