### ISSUE TITLE
New Feature !! OVF Supports

### ISSUE THREAD

**Issue by Hemant2000-karens** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#11]
If possible, then provides option to import ready made vm, by using OVF format, just happens in VMware or virtual box. it will be much better, and we will get some more options to do.

**Comment by ryecoaaron** [comment]
ova/ovf is a native VMware format.  virt-v2v does support converting the files.  An ova file is just a tar file and the kvm plugin already supports converting the virtual disk images.  Converting the vmx file is hit or miss and most of the time, it is just easier to create a new VM and attach the converted disks.  What appliance do you want to use?
