### ISSUE TITLE
[New Feature]Add a button to force refresh lxc image list

### ISSUE THREAD

**Issue by alphaarea** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#12]
When the network connection is poor, `fillImages()` may fetch an empty images index.

I manual remove `lxc_image_cache` to force refresh, and it get the right index
`rm /var/cache/openmediavault/lxc_image_cache`

add a button on webui can make it easier to use

**Comment by ryecoaaron** [comment]
Just out of curiosity, what does /var/cache/openmediavault/lxc_image_cache look like when you have a network issue?

**Comment by ryecoaaron** [comment]
I added retries if there is a failure - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kvm/commit/ef6a0cf025866a763fd50ee2abd5ac51d0934d82#diff-3944fac8f5160044a3b98d6034341b2b298ff58cf1725534cf91a484ccc83720R2991

Still looking at button options.

**Comment by ryecoaaron** [comment]
Button added to Settings tab - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kvm/commit/c53506086e2df6eaa6fc8ed8bf4b35e1f984601c.  Will release in a bit.
