### ISSUE TITLE
Not showing notification if start VM failed

### ISSUE THREAD

**Issue by chipx** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#2]
Default network is not running by default. If create VM and run it - nothing doing and not showing notification. After activating the network, the machine starts up.

**Comment by ryecoaaron** [comment]
Hopefully this is better in version 6.1 of the plugin that I just released.

**Comment by ryecoaaron** [comment]
Closing since I have not seen this issue and nothing on forum.
