### ISSUE TITLE
Add host disk and /dev/sd* device names

### ISSUE THREAD

**Issue by alexshalex** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#21]
Some sources indicate that /dev/sd* device names are unstable.
https://unix.stackexchange.com/a/639516
https://forums.debian.net/viewtopic.php?p=752395&sid=9d8822170587787eaa001d4d1528ceb9#p752395
At home, I also sometimes found that /dev/sd* device names changed.
Won't this create a problem if the plugin uses just the /dev/sd* device names when connecting host disks?
Maybe it's better to use /dev/disk/by-id/ names?
Thanks
p.s. my nickname on the forum is alexicon

**Comment by ryecoaaron** [comment]
Good point.  I was populating the list with [lsblk](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kvm/blob/main/usr/share/openmediavault/engined/rpc/kvm.inc#L1585) but I can look having it map that output to the by-id path.

**Comment by ryecoaaron** [comment]
I wrote a script to enumerate the disks.  It will list the by-id, by-path, and regular device paths to give flexibility.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kvm/commit/f28a7b11eef07588a3a28c98dc891eb5ba66050
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kvm/commit/17c0f67000763476fd2571594030b56b78f87041
