### ISSUE TITLE
Autostart VM is not automatically starting

### ISSUE THREAD

**Issue by legop3** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#26]
Hello, I have a Home Assistant VM that I set to autostart, but it is not starting when my OMV host boots. I have tried toggling the option off and back on, and I don't see anything in the XML about it, so I assume that the plugin is the one handling the autostarting. thanks.

**Comment by ryecoaaron** [comment]
The plugin just uses libvirt to enable autostart.  It creates a symlink in /etc/libvirt/qemu/autostart/.  This tells libvirtd to start the machine.  There are a few reasons the VM still might start.  Read - https://forum.openmediavault.org/index.php?thread/52556-kvm-autostart-doesnt-work/
