### ISSUE TITLE
Add ISO + add button

### ISSUE THREAD

**Issue by Hemant2000-karens** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#5]
Add button for iSO file, to make vm bootable

**Comment by Hemant2000-karens** [comment]
this time @ryecoaaron I have done same what you have said, and now it added iso, but after creating VM, when I try to start then this errors come here.

Now ??

<img width="1205" alt="Screenshot 2022-04-10 at 2 37 30 PM" src="https://user-images.githubusercontent.com/58652350/162611098-2c52145c-f686-4c7f-8c2a-3985e2986566.png">

**Comment by Hemant2000-karens** [comment]
now how I can give permission to execute this ?

**Comment by ryecoaaron** [comment]
None of this is a bug.  I really wish you would post on the forum if you need help using the plugin.

The plugin isn't going to re-implement shared folders.  All you have to do is create a shared folder from the same folder as the pool.  Then share it via samba or nfs.  You can drag the iso to the pool then

The error message is telling you the problem.  You need to give libvirt-qemu permissions to the iso.  If you just make it 644, it would be fine.
