### ISSUE TITLE
KVM denote have resolution or graphics settings

### ISSUE THREAD

**Issue by Hemant2000-karens** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#6]
Kvm is not supporting graphics options, or changing the resolution of my vm after installation, rest all are good 👍 

Just fix it, otherwise it will create problem, at some circumstance.

<img width="1151" alt="Screenshot 2022-04-12 at 4 46 37 PM" src="https://user-images.githubusercontent.com/58652350/162949110-90ee5a26-c61d-4e4f-a0b4-71ae6b9917c7.png">
![Screenshot 2022-04-12 at 4 46 19 PM](https://user-images.githubusercontent.com/58652350/162949115-6d89a4bc-10a2-46ea-896e-01c04d65c7ee.png)

@ryecoaaron

**Comment by ryecoaaron** [comment]
> Kvm is not supporting graphics options, or changing the resolution of my vm after installation

I'm not sure why you won't post on the on forum for issues like this.  This is not a bug.  You need to install the virtio drivers.  There is even a button on the Pools tab to download the virtio win iso.  After that you can attach the iso and install the drivers.  The plugin doesn't touch the guest VMs.

> Just fix it

"Please fix it" is the proper term.  Your term is a command not a polite request.

**Comment by Hemant2000-karens** [comment]
because, I believe in you, and @votdev, that you will surely help me, and if you have problem with just fix it, so let me tell you, that I have never said this, in a commanding way, or rudely, yeah I accept that I write like this, but believe me, I never disrespected you both.

**Comment by ryecoaaron** [comment]
> I believe in you, that you will surely help me

That is great but I shouldn't have to be the only one to support everything you need.  Not very many people look these issues because I am the only one maintaining these plugins.  But there are many people who could help on the forum.
