### ISSUE TITLE
Usb remove error, unable to remove usb from vm

### ISSUE THREAD

**Issue by Hemant2000-karens** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#7]
In lvm when I attach usb no problem, but after that I can't detach in lvm dashboard.

first I thought that without removing here, I pulled so this message pops. but when I re-inserted the USB, and with correct ID also, it not remove the usb, as it do for iSO.

<img width="1146" alt="Screenshot 2022-06-03 at 8 55 01 PM" src="https://user-images.githubusercontent.com/58652350/171994653-2b214c53-15cf-4928-8999-d5021681d9bd.png">

**Comment by ryecoaaron** [comment]
Unplugging the usb device won't remove the device from the VM's config.  You have to remove it using the Remove USB function before you can add it again.  Not much the plugin can do about that since it doesn't know that you unplugged it.
