### ISSUE TITLE
I can't install KVM

### ISSUE THREAD

**Issue by Joci78** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#8]
OMV v6.0.41-1 (Shaitan)

![problem](https://user-images.githubusercontent.com/83783991/192094138-d2cee40a-5973-401b-adc2-3ebb40fe407f.jpg)

**Comment by ryecoaaron** [comment]
It looks like you have the testing (bookworm) repo enabled or was enabled at some point and you installed some of the qemu packages from that repo.  I recommend disabling the testing repo (undo what you did to enable it) and enabling the backports repo (checkbox in omv-extras).  Then you will have to force install the packages it is complaining about.

sudo apt-get install qemu=1:6.2+dfsg-2~bpo11+1 qemu-system-data=1:7.0+dfsg-2~bpo11+2 qemu-system-ppc=1:7.0+dfsg-2~bpo11+2 qemu-system-x86=qemu-system-x86

There might be more packages to add to this list.  It should look like this:

libvirt-daemon-driver-qemu  8.0.0-1~bpo11+1
qemu  1:6.2+dfsg-2~bpo11+1
qemu-efi  2020.11-2+deb11u1
qemu-efi-aarch64  2020.11-2+deb11u1
qemu-efi-arm  2020.11-2+deb11u1
qemu-guest-agent  1:7.0+dfsg-2~bpo11+2
qemu-system-arm  1:7.0+dfsg-2~bpo11+2
qemu-system-common  1:7.0+dfsg-2~bpo11+2
qemu-system-data  1:7.0+dfsg-2~bpo11+2
qemu-system-mips  1:7.0+dfsg-2~bpo11+2
qemu-system-misc  1:7.0+dfsg-2~bpo11+2
qemu-system-ppc  1:7.0+dfsg-2~bpo11+2
qemu-system-x86  1:7.0+dfsg-2~bpo11+2
qemu-utils  1:7.0+dfsg-2~bpo11+2

**Comment by Joci78** [comment]
The test repo was not enabled! I experienced this even with a completely new installation. :(

**Comment by ryecoaaron** [comment]
> The test repo was not enabled!

That is why I said "It looks like".  Since I can't see your system, all I can do is speculate. My bad...

We don't need to work on this problem on github and the forum.  Since this isn't a plugin problem, I am closing this issue.

**Comment by Joci78** [comment]
Ok
