### ISSUE TITLE
dnsmasq occupying port 53.

### ISSUE THREAD

**Issue by tomikaka22** [OpenMediaVault-Plugin-Developers/openmediavault-kvm#9]
Please add an option to disable dnsmasq, or add an option to disable LXC altogether because it prevents users from running their dns server. 

I also suspect that dnsmasq prevents network cards from being passed through to VM's, causing me lots of headaches and downtime.

**Comment by ryecoaaron** [comment]
The kvm plugin does not install a dns server.  It only adds the dnsmasq-base package which has no server component (provided by the dnsmasq package).  OMV itself does use systemd-resolved which has a caching dns server that is using port 53.

**Comment by ryecoaaron** [comment]
If you see something using port 53 with a process named dnsmasq, this is on the vm and/or lxc subnet and not interferring with anything.  There is also no lxc service to disable.  If you are not running any lxc containers, nothing lxc is running.

Why are you using the testing repo version of the kvm plugin if you don't want lxc?

**Comment by ryecoaaron** [comment]
There have been updates to OMV in that timeframe as well.  It is very possible that networking was updated and started systemd-resolved.

But you have your VM setup wrong if port 53 on the host is causing problems for port 53 on a VM.  If you are using the default NAT network, that is part of your problem.  You really should setup a bridge network for your VMs.  There is a howto on the forum.

**Comment by tomikaka22** [comment]
Yes it is possible that OMV broke something. 

You misunderstood me. Adguard is outside of my VM, and I do have a bridge set up. 
However I became suspicious when OPNsense reported my interface is down. So I checked with the 'lspci' command that my network card was indeed detected, so the conclusion I came to is that something broke in the plugin. Later I checked with the 'fuser' command what was using port 53, and it reported dnsmasq. I was not running dnsmasq either on my VM, or my host. So I checked the commit history here, and I see dnsmasq as an added dependency, you can see how I arrived to my conclusion. I'd like to add that when I uninstalled the plugin dnsmasq disappeared, and Adguard worked as it should.

**Comment by tomikaka22** [comment]
I have a bridge set up on my built in NIC, and I used to have my PCIe Intel 2.5G NIC passed through. I was also not using dnsmasq on opnsense, I was using unbound which comes enabled by default.

**Comment by ryecoaaron** [comment]
>  Later I checked with the 'fuser' command what was using port 53, and it reported dnsmasq.

You can't just look at the port 53.  You need to look at the ip address for that process.  I have dnsmasq on port 53 on my machines too but they are on the virtual subnets.

> So I checked the commit history here, and I see dnsmasq as an added dependency

Not sure what you are looking at but dnsmasq-base was a dependency in the very first commit of the plugin's code.

> You misunderstood me.

With the limited info I have, I made some assumptions.

**Comment by tomikaka22** [comment]
I'll return with more info on the weekend, thanks for responding so quick!

**Comment by ryecoaaron** [comment]
Can you tell me if the dnsmasq (not dnsmasq-base) package is installed on your system?

**Comment by tomikaka22** [comment]
![image](https://user-images.githubusercontent.com/46684016/201742283-a1befa13-1dfe-4cdb-a69a-8d6709d20f31.png)
I don't think so, but there is a package named dnsmasq/stable when I type: `sudo apt list | grep dns`
![image](https://user-images.githubusercontent.com/46684016/201742681-8272306f-3d98-4e2c-ae13-8728e9fcefc0.png)

**Comment by ryecoaaron** [comment]
dpkg -l | grep dnsmasq is the best way to get the installation status.

**Comment by namnguyen51** [comment]
![image](https://user-images.githubusercontent.com/24988688/204027307-3c36401e-89a3-4073-be94-e245cbda33fe.png)
i had the same problem. 
lxc-net.service started dnsmasq and took over port 53.

**Comment by namnguyen51** [comment]
@tomikaka22 in my case, since i don't need lxc, i disable both lxc and lxc-net service with following commands:
systemctl disable lxc
systemctl mask lxc
systemctl disable lxc-net
systemctl mask lxc-net
@ryecoaaron Can you add a setting to disable lxc related services on the plugin's interface? thank you very much

**Comment by ryecoaaron** [comment]
Please show me the output where dnsmasq is listening on port 53 on the host's subnet.  sudo ss -lpn | grep ":53"

**Comment by namnguyen51** [comment]
![image](https://user-images.githubusercontent.com/24988688/204065715-457448bb-adb2-4b6b-8393-553e4ba488d4.png)
![image](https://user-images.githubusercontent.com/24988688/204065768-82b92209-2828-4266-ba43-7d333413b9ce.png)

**Comment by ryecoaaron** [comment]
lsof for port 53 doesn't mean anything since it could be on a different subnet.  And you didn't give me the output of ip a.  Is the ip address of the system 10.0.3.1?

**Comment by ryecoaaron** [comment]
Look at the full command lxc-net is running:

dnsmasq --conf-file=/dev/null -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/lxc/dnsmasq.pid **--listen-address 10.0.3.1** --dhcp-range 10.0.3.2,10.0.3.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --**interface=lxcbr0** --dhcp-leasefile=/var/lib/misc/dnsmasq.lxcbr0.leases --dhcp-authoritative

It is ONLY listening on 10.0.3.1 and only on the lxc bridge (lxcbr0).  You shouldn't have a problem with dnsmasq running unless your dns server is listening on all network interfaces.

**Comment by namnguyen51** [comment]
root@nsv:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master bond0 state DOWN group default qlen 1000
    link/ether a0:36:9f:30:1d:a6 brd ff:ff:ff:ff:ff:ff
3: enp3s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP group default qlen 1000
    link/ether 70:85:c2:6a:1f:4c brd ff:ff:ff:ff:ff:ff
4: eno1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond0 state UP group default qlen 1000
    link/ether 76:68:2a:70:94:62 brd ff:ff:ff:ff:ff:ff permaddr 70:85:c2:6a:1f:4e
    altname enp0s31f6
5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
    link/ether 76:68:2a:70:94:62 brd ff:ff:ff:ff:ff:ff
6: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 6e:a2:12:c6:c2:3d brd ff:ff:ff:ff:ff:ff
    inet 192.168.31.5/24 brd 192.168.31.255 scope global br0
       valid_lft forever preferred_lft forever
7: wlp4s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 60:f6:77:a3:59:49 brd ff:ff:ff:ff:ff:ff
8: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:38:ef:18 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe38:ef18/64 scope link
       valid_lft forever preferred_lft forever
9: lxcbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 brd 10.0.3.255 scope global lxcbr0
       valid_lft forever preferred_lft forever
10: br-08976dee1144: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:65:13:82:f6 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 brd 172.19.255.255 scope global br-08976dee1144
       valid_lft forever preferred_lft forever
    inet6 fe80::42:65ff:fe13:82f6/64 scope link
       valid_lft forever preferred_lft forever
11: br-1045a5875e0b: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:70:d6:05:23 brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.1/16 brd 172.21.255.255 scope global br-1045a5875e0b
       valid_lft forever preferred_lft forever
    inet6 fe80::42:70ff:fed6:523/64 scope link
       valid_lft forever preferred_lft forever
12: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:8c:0a:87:46 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:8cff:fe0a:8746/64 scope link
       valid_lft forever preferred_lft forever
13: br-5aa0f1aacd96: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:99:64:84:ea brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/16 brd 172.20.255.255 scope global br-5aa0f1aacd96
       valid_lft forever preferred_lft forever
    inet6 fe80::42:99ff:fe64:84ea/64 scope link
       valid_lft forever preferred_lft forever
14: br-8c87f71e0109: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:47:d9:37:a0 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-8c87f71e0109
       valid_lft forever preferred_lft forever
    inet6 fe80::42:47ff:fed9:37a0/64 scope link
       valid_lft forever preferred_lft forever
16: veth8b3aead@if15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-8c87f71e0109 state UP group default
    link/ether 76:69:0e:76:56:36 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::7469:eff:fe76:5636/64 scope link
       valid_lft forever preferred_lft forever
18: vetha6d3c3e@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether 76:81:5f:ba:a8:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::7481:5fff:feba:a804/64 scope link
       valid_lft forever preferred_lft forever
20: vethbf06c35@if19: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-08976dee1144 state UP group default
    link/ether 6a:0d:52:07:66:11 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::680d:52ff:fe07:6611/64 scope link
       valid_lft forever preferred_lft forever
22: veth9fdc8e9@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-5aa0f1aacd96 state UP group default
    link/ether 32:d1:02:ce:bf:63 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::30d1:2ff:fece:bf63/64 scope link
       valid_lft forever preferred_lft forever
24: veth883e2b8@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-1045a5875e0b state UP group default
    link/ether 36:f5:0c:3d:ad:c2 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::34f5:cff:fe3d:adc2/64 scope link
       valid_lft forever preferred_lft forever

**Comment by namnguyen51** [comment]
root@nsv:~# sudo ss -lpn | grep ":53"
udp   UNCONN 0      0                                                                                10.0.3.1:53               0.0.0.0:*    users:(("dnsmasq",pid=1818,fd=6))

udp   UNCONN 0      0                                                                                 0.0.0.0:5353             0.0.0.0:*    users:(("avahi-daemon",pid=1409,fd=12))

udp   UNCONN 0      0                                                                                 0.0.0.0:5355             0.0.0.0:*    users:(("systemd-resolve",pid=1389,fd=11))

udp   UNCONN 0      0                                                                                    [::]:5353                [::]:*    users:(("avahi-daemon",pid=1409,fd=13))

udp   UNCONN 0      0                                                                                    [::]:5355                [::]:*    users:(("systemd-resolve",pid=1389,fd=13))

tcp   LISTEN 0      4096                                                                              0.0.0.0:5355             0.0.0.0:*    users:(("systemd-resolve",pid=1389,fd=12))

tcp   LISTEN 0      32                                                                               10.0.3.1:53               0.0.0.0:*    users:(("dnsmasq",pid=1818,fd=7))

tcp   LISTEN 0      5                                                                                10.0.3.1:5357             0.0.0.0:*    users:(("python3",pid=1751,fd=14))

tcp   LISTEN 0      5                                                                              172.21.0.1:5357             0.0.0.0:*    users:(("python3",pid=1751,fd=26))

tcp   LISTEN 0      5                                                                              172.19.0.1:5357             0.0.0.0:*    users:(("python3",pid=1751,fd=22))

tcp   LISTEN 0      5                                                                              172.20.0.1:5357             0.0.0.0:*    users:(("python3",pid=1751,fd=34))

tcp   LISTEN 0      5                                                                            192.168.31.5:5357             0.0.0.0:*    users:(("python3",pid=1751,fd=10))

tcp   LISTEN 0      5                                                                              172.17.0.1:5357             0.0.0.0:*    users:(("python3",pid=1751,fd=30))

tcp   LISTEN 0      5                                                                              172.18.0.1:5357             0.0.0.0:*    users:(("python3",pid=1751,fd=38))

tcp   LISTEN 0      5                                                 [fe80::680d:52ff:fe07:6611]%vethbf06c35:5357                [::]:*    users:(("python3",pid=1751,fd=78))

tcp   LISTEN 0      5                                                [fe80::42:70ff:fed6:523]%br-1045a5875e0b:5357                [::]:*    users:(("python3",pid=1751,fd=58))

tcp   LISTEN 0      4096                                                                                 [::]:5355                [::]:*    users:(("systemd-resolve",pid=1389,fd=14))

tcp   LISTEN 0      5                                                  [fe80::7469:eff:fe76:5636]%veth8b3aead:5357                [::]:*    users:(("python3",pid=1751,fd=66))

tcp   LISTEN 0      5                                                  [fe80::30d1:2ff:fece:bf63]%veth9fdc8e9:5357                [::]:*    users:(("python3",pid=1751,fd=70))

tcp   LISTEN 0      5                                                         [fe80::fc54:ff:fe38:ef18]%vnet0:5357                [::]:*    users:(("python3",pid=1751,fd=18))

tcp   LISTEN 0      5                                               [fe80::42:47ff:fed9:37a0]%br-8c87f71e0109:5357                [::]:*    users:(("python3",pid=1751,fd=50))

tcp   LISTEN 0      5                                               [fe80::42:65ff:fe13:82f6]%br-08976dee1144:5357                [::]:*    users:(("python3",pid=1751,fd=46))

tcp   LISTEN 0      5                                                  [fe80::34f5:cff:fe3d:adc2]%veth883e2b8:5357                [::]:*    users:(("python3",pid=1751,fd=62))

tcp   LISTEN 0      5                                               [fe80::42:99ff:fe64:84ea]%br-5aa0f1aacd96:5357                [::]:*    users:(("python3",pid=1751,fd=42))

tcp   LISTEN 0      5                                                 [fe80::7481:5fff:feba:a804]%vetha6d3c3e:5357                [::]:*    users:(("python3",pid=1751,fd=74))

tcp   LISTEN 0      5                                                       [fe80::42:8cff:fe0a:8746]%docker0:5357                [::]:*    users:(("python3",pid=1751,fd=54))

**Comment by namnguyen51** [comment]
Let me be more clear about my case, in the past I used to use docker to run adguardhome on my nas. Adguard listens on port 53. It was working fine until recently when I updated the kvm plugin to a version that supports lxc. After reboot, Adguardhome stopped working, here is the result after I look at the docker log:
![image](https://user-images.githubusercontent.com/24988688/204066750-c9e86a1f-c25a-49e7-83b9-28c47e0cad64.png)
After I disabled 2 services lxc and lxc-net as my comment above and rebooted the system, Adguardhome worked again.

**Comment by ryecoaaron** [comment]
Are you using net host for your adguard container?  If so, it will try to listen on all network interfaces.  I really don't like changing the plugin in an ugly way to accommodate a container doing the wrong thing.

**Comment by namnguyen51** [comment]
I searched on google and found there are many similar cases of LXC and dnsmasq using port 53, for example:
https://askubuntu.com/questions/1328091/lxc-dnsmasq-port-53-in-use-but-i-would-like-to-map-to-container
https://github.com/lxc/lxd/issues/4090

**Comment by namnguyen51** [comment]
> Are you using net host for your adguard container? If so, it will try to listen on all network interfaces. I really don't like changing the plugin in an ugly way to accommodate a container doing the wrong thing.

I use network host for AdguardHome to be able to display correct client ip on dashboard.
In this case, I simply disabled the lxc service as I did above. Thank you very much.
To those who have the same problem and don't want to disable lxc service, the easiest way is to move AdguardHome from docker to lxc :D

**Comment by namnguyen51** [comment]
@ryecoaaron Because there's no problem anymore, I think I should delete the ip comments above, better safe than sorry :D

**Comment by ryecoaaron** [comment]
Your link is not the same.  They are seeing an entry of 0.0.0.0:53 which means dnsmasq is listening on all interfaces.  dnsmasq from lxc is not doing this.

and running adguardhome in lxc is not the only way to fix the issue.  You could use docker macvlan or specify the ports instead of --net=host.  Or you can just disable lxc services like you did.  I really don't want to spend hours and hours splitting kvm and lxc into separate plugins.  They share a lot of code as well.

**Comment by ryecoaaron** [comment]
>  Because there's no problem anymore, I think I should delete the ip comments above, better safe than sorry

Go for it.  They are nat'd ip addresses and not addressable from the internet though.

**Comment by tomikaka22** [comment]
> @tomikaka22 in my case, since i don't need lxc, i disable both lxc and lxc-net service with following commands:
> systemctl disable lxc
> systemctl disable lxc-net

Yes, this disables lxc, and therefore my Adguard that runs in host mode is able to bind to port 53. However, I still think this is worth a toggle in the plugin settings. Not everyone needs lxc, and turning it off with a switch is far easier than scouring the internet on how to do it.

**Comment by ryecoaaron** [comment]
I get it but disabling lxc and lxc-net leaves the plugin in a weird state.  It would be very difficult to disable just the lxc features of the plugin when the services are disabled.  I will see what I can do but this still sucks that I have to do all of th work.

**Comment by tomikaka22** [comment]
Thank you very much! We are very grateful for your hard work!

**Comment by ryecoaaron** [comment]
Version 6.2.5 of the plugin is in the repo.  There is a settings tab that allows you to change the status of the lxc and lxc-net services.
